In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import gradio as gr

C:\Users\Yash\Tensorflow_project\tfenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
articles_df = pd.read_csv("C:/Users/Yash/Downloads/shared_articles.csv")
# articles_df['text'].head(1)
articles_df.head(4)['text'].values

array(['All of this work is still very early. The first full public version of the Ethereum software was recently released, and the system could face some of the same technical and legal problems that have tarnished Bitcoin. Many Bitcoin advocates say Ethereum will face more security problems than Bitcoin because of the greater complexity of the software. Thus far, Ethereum has faced much less testing, and many fewer attacks, than Bitcoin. The novel design of Ethereum may also invite intense scrutiny by authorities given that potentially fraudulent contracts, like the Ponzi schemes, can be written directly into the Ethereum system. But the sophisticated capabilities of the system have made it fascinating to some executives in corporate America. IBM said last year that it was experimenting with Ethereum as a way to control real world objects in the so-called Internet of things. Microsoft has been working on several projects that make it easier to use Ethereum on its computing cloud, Azu

In [3]:
# Dropped rows with duplicate 'title' and 'text', keeping only the first occurrence
articles_df = articles_df[~articles_df.duplicated(subset=['title', 'text'], keep='first')].reset_index(drop=True)
articles_df['title'] = articles_df['title'].dropna()
articles_df

timestamp        eventType            contentId       authorPersonId  \
0     1459192779  CONTENT REMOVED -6451309518266745024  4340306774493623681   
1     1459194146   CONTENT SHARED -7292285110016212249  4340306774493623681   
2     1459194474   CONTENT SHARED -6151852268067518688  3891637997717104548   
3     1459194497   CONTENT SHARED  2448026894306402386  4340306774493623681   
4     1459194522   CONTENT SHARED -2826566343807132236  4340306774493623681   
...          ...              ...                  ...                  ...   
3021  1487946604   CONTENT SHARED  9213260650272029784  3609194402293569455   
3022  1487947067   CONTENT SHARED -3295913657316686039  6960073744377754728   
3023  1488223224   CONTENT SHARED  3618271604906293310  1908339160857512799   
3024  1488300719   CONTENT SHARED  6607431762270322325 -1393866732742189886   
3025  1488307871   CONTENT SHARED  4109618890343020064  3891637997717104548   

          authorSessionId                                    authorUserAgent  \
0     8940341205206233829                                                NaN   
1     8940341205206233829                                                NaN   
2    -1457532940883382585                                                NaN   
3     8940341205206233829                                                NaN   
4     8940341205206233829                                                NaN   
...                   ...                                                ...   
3021  7144190892417579456  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...   
3022 -8193630595542572738  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3...   
3023  -183341653743161643  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0...   
3024  2367029511384577082  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   
3025 -7416795577834806518  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...   

     authorRegion authorCountry contentType  \
0             NaN           NaN        HTML   
1             NaN           NaN        HTML   
2             NaN           NaN        HTML   
3             NaN           NaN        HTML   
4             NaN           NaN        HTML   
...           ...           ...         ...   
3021           SP            BR        HTML   
3022           GA            US        HTML   
3023           SP            BR        HTML   
3024           MG            BR        HTML   
3025           SP            BR        HTML   

                                                    url  \
0     http://www.nytimes.com/2016/03/28/business/dea...   
1     http://cointelegraph.com/news/bitcoin-future-w...   
2     https://cloudplatform.googleblog.com/2016/03/G...   
3     https://bitcoinmagazine.com/articles/ibm-wants...   
4     http://www.coindesk.com/ieee-blockchain-oxford...   
...                                                 ...   
3021  https://startupi.com.br/2017/02/liga-ventures-...   
3022  https://thenextweb.com/apps/2017/02/14/amazon-...   
3023                        https://code.org/about/2016   
3024  https://www.bloomberg.com/news/articles/2017-0...   
3025  https://www.acquia.com/blog/partner/2017-acqui...   

                                                  title  \
0     Ethereum, a Virtual Currency, Enables Transact...   
1     Bitcoin Future: When GBPcoin of Branson Wins O...   
2                          Google Data Center 360° Tour   
3     IBM Wants to "Evolve the Internet" With Blockc...   
4     IEEE to Talk Blockchain at Cloud Computing Oxf...   
...                                                 ...   
3021  Conheça a Liga IoT, plataforma de inovação abe...   
3022  Amazon takes on Skype and GoToMeeting with its...   
3023                        Code.org 2016 Annual Report   
3024  JPMorgan Software Does in Seconds What Took La...   
3025               The 2017 Acquia Partners of the Year   

                                                   text lang  
0     All of this work is still very early. The fir

In [4]:
vectorizer = TfidfVectorizer(stop_words = "english")

In [5]:
articles_df['text'] = articles_df["text"].fillna(" ")
tfid_matrix = vectorizer.fit_transform(articles_df['text'])

In [6]:
print(tfid_matrix)

  (0, 5908)	0.014483965745159734
  (0, 3188)	0.017965771992699726
  (0, 20370)	0.01684005349635588
  (0, 19431)	0.023418177126715997
  (0, 71545)	0.011761583068954628
  (0, 235)	0.012049547387342093
  (0, 39555)	0.0142117729996426
  (0, 28222)	0.022424344295473513
  (0, 12446)	0.01930638315433926
  (0, 57925)	0.0359395353212173
  (0, 52025)	0.015185594125140136
  (0, 12128)	0.033658686778953006
  (0, 65217)	0.013457407393782102
  (0, 63512)	0.013523950693742999
  (0, 12099)	0.02396226351258414
  (0, 54264)	0.012439158624911182
  (0, 17895)	0.02832730616569357
  (0, 17619)	0.03060815470795786
  (0, 62705)	0.02202210442693659
  (0, 62115)	0.024215512193316833
  (0, 56088)	0.023800487473335956
  (0, 58547)	0.017193857789709284
  (0, 9856)	0.07683697227050369
  (0, 19165)	0.017033418987109483
  (0, 17639)	0.038418486135251846
  :	:
  (3024, 39021)	0.05242314236385844
  (3024, 54453)	0.018720034838836688
  (3024, 61152)	0.08867467152148387
  (3024, 71105)	0.036848862328282786
  (3025, 14985

In [7]:
cosine_simm = linear_kernel(tfid_matrix,tfid_matrix)
print(cosine_simm)

[[1.         0.03004292 0.01604768 ... 0.05108797 0.08973755 0.02015469]
 [0.03004292 1.         0.02349927 ... 0.02705937 0.03340464 0.01140893]
 [0.01604768 0.02349927 1.         ... 0.02251768 0.04506884 0.        ]
 ...
 [0.05108797 0.02705937 0.02251768 ... 1.         0.05938275 0.07890865]
 [0.08973755 0.03340464 0.04506884 ... 0.05938275 1.         0.04332828]
 [0.02015469 0.01140893 0.         ... 0.07890865 0.04332828 1.        ]]


In [8]:
articles_df.head(5)

timestamp        eventType            contentId       authorPersonId  \
0  1459192779  CONTENT REMOVED -6451309518266745024  4340306774493623681   
1  1459194146   CONTENT SHARED -7292285110016212249  4340306774493623681   
2  1459194474   CONTENT SHARED -6151852268067518688  3891637997717104548   
3  1459194497   CONTENT SHARED  2448026894306402386  4340306774493623681   
4  1459194522   CONTENT SHARED -2826566343807132236  4340306774493623681   

       authorSessionId authorUserAgent authorRegion authorCountry contentType  \
0  8940341205206233829             NaN          NaN           NaN        HTML   
1  8940341205206233829             NaN          NaN           NaN        HTML   
2 -1457532940883382585             NaN          NaN           NaN        HTML   
3  8940341205206233829             NaN          NaN           NaN        HTML   
4  8940341205206233829             NaN          NaN           NaN        HTML   

                                                 url  \
0  http://www.nytimes.com/2016/03/28/business/dea...   
1  http://cointelegraph.com/news/bitcoin-future-w...   
2  https://cloudplatform.googleblog.com/2016/03/G...   
3  https://bitcoinmagazine.com/articles/ibm-wants...   
4  http://www.coindesk.com/ieee-blockchain-oxford...   

                                               title  \
0  Ethereum, a Virtual Currency, Enables Transact...   
1  Bitcoin Future: When GBPcoin of Branson Wins O...   
2                       Google Data Center 360° Tour   
3  IBM Wants to "Evolve the Internet" With Blockc...   
4  IEEE to Talk Blockchain at Cloud Computing Oxf...   

                                                text lang  
0  All of this work is still very early. The firs...   en  
1  The alarm clock wakes me at 8:00 with stream o...   en  
2  We're excited to share the Google Data Center ...   en  
3  The Aite Group projects the blockchain market ...   en  
4  One of the largest and oldest organizations fo...   en

In [9]:
indices = pd.Series(articles_df.index, index = articles_df['title'])
indices

title
Ethereum, a Virtual Currency, Enables Transactions That Rival Bitcoin's                                         0
Bitcoin Future: When GBPcoin of Branson Wins Over USDcoin of Trump                                              1
Google Data Center 360° Tour                                                                                    2
IBM Wants to "Evolve the Internet" With Blockchain Technology                                                   3
IEEE to Talk Blockchain at Cloud Computing Oxford-Con - CoinDesk                                                4
                                                                                                             ... 
Conheça a Liga IoT, plataforma de inovação aberta que irá acelerar projetos ligados a Internet das Coisas    3021
Amazon takes on Skype and GoToMeeting with its Chime video conferencing app                                  3022
Code.org 2016 Annual Report                                                       

In [10]:
indices['Google Data Center 360° Tour']

2

In [11]:
def get_recommendation(title, cosine_sim = cosine_simm):
    recomm_title_list = []
    idx = indices[title]
    
    similar_scores = enumerate(cosine_sim[idx])
    similar_scores = sorted(similar_scores, key = lambda x:x[1], reverse = True)
    similar_scores = similar_scores[1:6]
    
    scores_id = [i[0] for i in similar_scores] 
    
    article_list = articles_df['title'].iloc[scores_id].reset_index()
    recomm_title_list = list(article_list['title'])
    
    content = articles_df[articles_df['title'] == title]
    text_content = content['text'].iloc[0]
    
    return recomm_title_list, text_content


In [12]:
get_recommendation('Bitcoin Future: When GBPcoin of Branson Wins Over USDcoin of Trump')

(["America's allies are preparing for a bumpy ride",
  "I've had the chance to troll Donald Trump. But I didn't.",
  'What A Difference 2 Percentage Points Makes',
  'How To Benefit From Getting Paid in Bitcoin',
  'Blockchain Will Be Used By 15% of Big Banks By 2017'],
 'The alarm clock wakes me at 8:00 with stream of advert-free broadcasting, charged at one satoshi per second. The current BTC exchange rate makes that snooze button a costly proposition! So I get up, make coffee and go to my computer to check the overnight performance of my bots. TradeBot earns me on Trump and Branson TradeBot, which allocates funds between the main chain and various national currency side-chains, generated a lucrative 0.24 BTC return. TradeBot has been reliably profitable ever since I set it to trade USDcoin according to political prediction market data. As expected, the latest poll numbers came in as highly supportive of Trump\'s re-election as USDcoin CEO. Trump\'s resistance to de-anonymizing publi

# Transformer Model: all-MiniLM-L6-v2

In [15]:
articles_df[['title','text']]

title  \
0     Ethereum, a Virtual Currency, Enables Transact...   
1     Bitcoin Future: When GBPcoin of Branson Wins O...   
2                          Google Data Center 360° Tour   
3     IBM Wants to "Evolve the Internet" With Blockc...   
4     IEEE to Talk Blockchain at Cloud Computing Oxf...   
...                                                 ...   
3021  Conheça a Liga IoT, plataforma de inovação abe...   
3022  Amazon takes on Skype and GoToMeeting with its...   
3023                        Code.org 2016 Annual Report   
3024  JPMorgan Software Does in Seconds What Took La...   
3025               The 2017 Acquia Partners of the Year   

                                                   text  
0     All of this work is still very early. The firs...  
1     The alarm clock wakes me at 8:00 with stream o...  
2     We're excited to share the Google Data Center ...  
3     The Aite Group projects the blockchain market ...  
4     One of the largest and oldest organizations fo...  
...                                                 ...  
3021  A Liga Ventures, aceleradora de startups espec...  
3022  Amazon has launched Chime, a video conferencin...  
3023  February 9, 2017 - We begin each year with a l...  
3024  At JPMorgan Chase & Co., a learning machine is...  
3025  The Acquia Partner Awards Program is comprised...  

[3026 rows x 2 columns]

In [16]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

article_list = []
article_list = list(articles_df['text'])
# print(article_list)

articles_embeddings = model.encode(article_list, batch_size=16, show_progress_bar=True, normalize_embeddings=True, convert_to_tensor = True)



Batches: 100%|███████████████████████████████████████████████████████████████████████| 190/190 [02:30<00:00,  1.26it/s]


In [17]:
similarities = model.similarity(articles_embeddings, articles_embeddings)
print(similarities.shape)

torch.Size([3026, 3026])


In [18]:
indices_lmv = pd.Series(articles_df.index, index = articles_df['title'])
indices_lmv

title
Ethereum, a Virtual Currency, Enables Transactions That Rival Bitcoin's                                         0
Bitcoin Future: When GBPcoin of Branson Wins Over USDcoin of Trump                                              1
Google Data Center 360° Tour                                                                                    2
IBM Wants to "Evolve the Internet" With Blockchain Technology                                                   3
IEEE to Talk Blockchain at Cloud Computing Oxford-Con - CoinDesk                                                4
                                                                                                             ... 
Conheça a Liga IoT, plataforma de inovação aberta que irá acelerar projetos ligados a Internet das Coisas    3021
Amazon takes on Skype and GoToMeeting with its Chime video conferencing app                                  3022
Code.org 2016 Annual Report                                                       

In [19]:
def get_recommendation_miniLM(title, cosine_sim = similarities):
    recomm_title_list = []
    idx = indices_lmv[title]
    
    similar_scores = enumerate(cosine_sim[idx])
    similar_scores = sorted(similar_scores, key = lambda x:x[1], reverse = True)
    similar_scores = similar_scores[1:6]
    
    scores_id = [i[0] for i in similar_scores] 
    
    article_list = articles_df['title'].iloc[scores_id].reset_index()
    recomm_title_list = list(article_list['title'])
    
    content = articles_df[articles_df['title'] == title]
    text_content = content['text'].iloc[0]
    
    return recomm_title_list, text_content

In [20]:
get_recommendation_miniLM('Bitcoin Future: When GBPcoin of Branson Wins Over USDcoin of Trump')

(['Google Failure, Ethereum Leaps, ECB Giveout in Cointelegraph Daily Digest',
  'This New Banking AI Is the Here and Now of Chatbots',
  'Why 2016 is shaping up to be the Year of the Bot',
  '3 Big Blockchain Ideas MIT is Working on Right Now - CoinDesk',
  "The Real Lesson for Data Science That is Demonstrated by Palantir's Struggles"],
 'The alarm clock wakes me at 8:00 with stream of advert-free broadcasting, charged at one satoshi per second. The current BTC exchange rate makes that snooze button a costly proposition! So I get up, make coffee and go to my computer to check the overnight performance of my bots. TradeBot earns me on Trump and Branson TradeBot, which allocates funds between the main chain and various national currency side-chains, generated a lucrative 0.24 BTC return. TradeBot has been reliably profitable ever since I set it to trade USDcoin according to political prediction market data. As expected, the latest poll numbers came in as highly supportive of Trump\'s r

In [21]:
get_recommendation('Bitcoin Future: When GBPcoin of Branson Wins Over USDcoin of Trump')

(["America's allies are preparing for a bumpy ride",
  "I've had the chance to troll Donald Trump. But I didn't.",
  'What A Difference 2 Percentage Points Makes',
  'How To Benefit From Getting Paid in Bitcoin',
  'Blockchain Will Be Used By 15% of Big Banks By 2017'],
 'The alarm clock wakes me at 8:00 with stream of advert-free broadcasting, charged at one satoshi per second. The current BTC exchange rate makes that snooze button a costly proposition! So I get up, make coffee and go to my computer to check the overnight performance of my bots. TradeBot earns me on Trump and Branson TradeBot, which allocates funds between the main chain and various national currency side-chains, generated a lucrative 0.24 BTC return. TradeBot has been reliably profitable ever since I set it to trade USDcoin according to political prediction market data. As expected, the latest poll numbers came in as highly supportive of Trump\'s re-election as USDcoin CEO. Trump\'s resistance to de-anonymizing publi

In [22]:
def recommend(title):
    content_recommendations = get_recommendation_miniLM(title)
    return content_recommendations[1], "\n\n".join(content_recommendations[0])

In [23]:
interface = gr.Interface(
    fn=recommend,
    inputs=gr.Dropdown(choices=list(articles_df['title']), label="Select Article Title"),
    outputs=[
        gr.Textbox(label="Article Content"),  # This output will be in a separate column
        gr.Textbox(label="Top 5 Recommendations")  # This output will be in a separate column
    ],
    title="Articles Recommendation Engine",
    description="Select an article to view its content and get personalized recommendations."
)

interface.launch()

* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
